-- Birr'e schema — baseline migration.
--
-- Forward-only from here: DO NOT edit this file to change existing tables.
-- To modify the schema, add a new file 00X_description.sql that alters it.
-- Each migration is idempotent (safe to re-run) using:
--   create table if not exists ...
--   create index if not exists ...
--   create or replace function ...
--   drop trigger if exists ...; create trigger ...
--   drop policy if exists ...; create policy ...
--
-- Apply via Supabase SQL editor or `supabase db push`.

-- ──────────────────────────────────────────────────────────────
-- profiles: 1:1 with auth.users; holds preferences + tax inputs
-- ──────────────────────────────────────────────────────────────
create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  theme text not null default 'light' check (theme in ('light','dark')),
  -- tax inputs
  filing_status text not null default 'single' check (filing_status in ('single','mfj','hoh')),
  state text not null default 'GA',
  annual_salary numeric(12,2),
  pay_frequency text not null default 'biweekly' check (pay_frequency in ('weekly','biweekly','semimonthly','monthly')),
  retirement_pct numeric(5,2) not null default 0,
  retirement_type text not null default 'roth' check (retirement_type in ('roth','traditional')),
  health_pct numeric(5,2) not null default 0,
  hsa_per_paycheck numeric(8,2) not null default 0,
  fica_exempt boolean not null default false,
  created_at timestamptz not null default now()
);

-- ──────────────────────────────────────────────────────────────
-- accounts: bank/card/cash/brokerage. Manual balance entry.
-- ──────────────────────────────────────────────────────────────
create table if not exists accounts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  type text not null check (type in ('checking','savings','credit','brokerage','cash','retirement')),
  balance numeric(12,2) not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);
create index if not exists accounts_user_id_idx on accounts(user_id);

-- ──────────────────────────────────────────────────────────────
-- goals: savings goals. saved_so_far is computed from transactions.
-- ──────────────────────────────────────────────────────────────
create table if not exists goals (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  icon text not null default '🎯',
  name text not null,
  target_amount numeric(12,2) not null,
  target_date date,
  status text not null default 'active' check (status in ('active','wishlist','complete','archived')),
  created_at timestamptz not null default now()
);
create index if not exists goals_user_id_idx on goals(user_id);

-- ──────────────────────────────────────────────────────────────
-- transactions: the source of truth for every page.
-- ──────────────────────────────────────────────────────────────
create table if not exists transactions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  account_id uuid references accounts(id) on delete set null,
  goal_id uuid references goals(id) on delete set null,
  date date not null,
  description text not null,
  amount numeric(12,2) not null,
  type text not null check (type in ('expense','income','transfer')),
  category text not null,
  note text,
  created_at timestamptz not null default now()
);
create index if not exists transactions_user_date_idx on transactions(user_id, date desc);
create index if not exists transactions_goal_idx on transactions(goal_id) where goal_id is not null;

-- ──────────────────────────────────────────────────────────────
-- budgets: per-category monthly limit.
-- ──────────────────────────────────────────────────────────────
create table if not exists budgets (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  category text not null,
  amount numeric(12,2) not null,
  unique(user_id, category)
);

-- ──────────────────────────────────────────────────────────────
-- recurring: pre-declared subscriptions / recurring bills.
-- ──────────────────────────────────────────────────────────────
create table if not exists recurring (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  amount numeric(12,2) not null,
  category text not null,
  frequency text not null default 'monthly' check (frequency in ('weekly','biweekly','monthly','yearly')),
  next_charge date,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
create index if not exists recurring_user_id_idx on recurring(user_id);

-- ──────────────────────────────────────────────────────────────
-- monthly_notes: free-form text for the Review page.
-- ──────────────────────────────────────────────────────────────
create table if not exists monthly_notes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  month date not null,
  content text not null default '',
  updated_at timestamptz not null default now(),
  unique(user_id, month)
);

-- ──────────────────────────────────────────────────────────────
-- Auto-create a profile row when a new auth user signs up.
-- ──────────────────────────────────────────────────────────────
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id) values (new.id);
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ──────────────────────────────────────────────────────────────
-- RLS — users can only see and modify their own rows.
-- ──────────────────────────────────────────────────────────────
alter table profiles      enable row level security;
alter table accounts      enable row level security;
alter table goals         enable row level security;
alter table transactions  enable row level security;
alter table budgets       enable row level security;
alter table recurring     enable row level security;
alter table monthly_notes enable row level security;

drop policy if exists "users can view own profile" on profiles;
create policy "users can view own profile"
  on profiles for select using (id = auth.uid());

drop policy if exists "users can update own profile" on profiles;
create policy "users can update own profile"
  on profiles for update using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists "users own accounts" on accounts;
create policy "users own accounts"
  on accounts for all using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "users own goals" on goals;
create policy "users own goals"
  on goals for all using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "users own transactions" on transactions;
create policy "users own transactions"
  on transactions for all using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "users own budgets" on budgets;
create policy "users own budgets"
  on budgets for all using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "users own recurring" on recurring;
create policy "users own recurring"
  on recurring for all using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "users own monthly_notes" on monthly_notes;
create policy "users own monthly_notes"
  on monthly_notes for all using (user_id = auth.uid()) with check (user_id = auth.uid());
